spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cepg-82265842-sa-std-rg-std-db.postgres.database.azure.com:5432/postgres
    username: postgres
    password: qwe123!@#
    hikari:
      maximum-pool-size: 2
      minimum-idle: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      # mode: always
      mode: embedded

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

pvc:
  path: /mnt/cloud-sample
